(OffscreenRendering) Fix compile error if GPU_MEMORY_PROFILE_ENABLED is ON
Looks offscreen rendering refresh rate become enum class instead of integer.
We need to define it's own string print logic to stream.

/home/hpich/work/dali-ui/dali-ui-foundation/internal/render-effects/offscreen-rendering-impl.cpp:160:47: error: invalid operands to binary expression ('basic_ostream<char, char_traits<char>>' and 'Ui::View::OffscreenRefreshRate')
  160 |     oss << "OffscreenRendering refresh rate:" << mRefreshRate;

Signed-off-by: Eunki Hong <eunkiki.hong@samsung.com>