(C++26)(UTC) Fix convert error from char8_t to char
u8"" type change as char8_t type at c++26. We need to  use it's own convert function to char*

/home/hpich/work/dali-ui/automated-tests/src/dali-ui-foundation-internal/utc-Dali-TextReveal-internal.cpp:2870:5: error: invalid conversion from ‘const char8_t*’ to ‘const char*’ [-fpermissive]
 2870 |     u8"אבג X ABC", {{4u, 1u}}, Size(420.0f, 120.0f));

Signed-off-by: Eunki Hong <eunkiki.hong@samsung.com>